import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AppProviders } from './provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MyApp',
  description: 'Generated by create next app for driveeTest',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProviders>
          {children}
        </AppProviders>
      </body>
    </html>
  )
}
